// Generated by LiveScript 1.2.0
(function(){
  (function($){
    var listenToTyping;
    $.fn.typing = function(options){
      return this.each(function(i, elem){
        listenToTyping(elem, options);
      });
    };
    return listenToTyping = function(elem, options){
      var settings, $elem, startTyping, stopTyping;
      settings = $.extend({
        start: null,
        stop: null,
        delay: 400
      }, options);
      $elem = $(elem);
      startTyping = function(event){
        if (settings.start) {
          settings.start(event, $elem);
        }
      };
      stopTyping = function(event, delay){
        var delayedCallback;
        clearTimeout(delayedCallback);
        delayedCallback = setTimeout(function(){
          if (settings.stop) {
            return settings.stop(event, $elem);
          }
        }, delay >= 0
          ? delay
          : settings.delay);
      };
      $elem.keydown(startTyping);
      $elem.keyup(stopTyping);
      return $elem.blur(function(event){
        stopTyping(event, 0);
      });
    };
  })(
  jQuery);
}).call(this);
